project:
  type: website
  output-dir: docs
  resources:
    - images/**

website:
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: images/power-rangers/red-contour.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: home
      - href: Courses.qmd
        text: Courses
      - href: https://enricotoffalini.github.io/slides/
        text: Slides
        target: _blank
      - href: https://enricotoffalini.github.io/blog/
        text: Blog
        target: _blank
      - href: CV.qmd
        text: CV
      - href: contact.qmd
        text: contact

format:
  html:
    include-in-header:
       text: |
         <link rel="shortcut icon" href="images/favicon.png"/> 
         <script data-goatcounter="https://enricotoffalini.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
         <meta name="google-site-verification" content="0Bgsc2FKbLDwGUtDSchwt68Oard7n2Q3eaEDg6KU7rE" />
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
