project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: Courses.qmd
        text: Courses
      - href: https://enricotoffalini.github.io/slides/
        text: Slides
        target: _blank
      - href: https://enricotoffalini.github.io/blog/
        text: Blog
        target: _blank
      - href: CV.qmd
        text: CV
      - href: contact.qmd
        text: contact

format:
  html:
    include-in-header:
       text: |
         <link rel="shortcut icon" href="images/favicon.png"/>
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
